version: "3.9"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
  app:
    build: .
    ports:
      - 5060:5050
    env_file:
      - .env
    depends_on:
      - mongo_db
volumes:
  mongo_db: {} 