
const ERROR_UNAUTHORIZED="Unauthorized"
const ERROR_INVALID_TOKEN="INVALID_TOKEN"
const ERROR_INVALID_PASSWORD="Invalid Password"
const ERROR_DOESNT_EXISTS="doesn't exist"
const ERROR_EXIST="already exist"


module.exports={ERROR_UNAUTHORIZED,ERROR_INVALID_TOKEN,ERROR_INVALID_PASSWORD,
    ERROR_DOESNT_EXISTS,ERROR_EXIST}